### ISSUE TITLE
SGX Enclave linked with lld does not work

### ISSUE THREAD

**Issue by LeoneChen** [intel/linux-sgx#777] opened 2022-01-15 12:25 UTC
Use SampleEnclave as example, I replaced the enclave linker from ld to llvm's lld, then Enclave break down when initializing.
![image](https://user-images.githubusercontent.com/35480440/149621436-f704856f-b879-4f23-9cbe-0f09003d94bf.png)

The broken reason is that `&__ImageBase` is `0`, so `g_enclave_base` etc. also become 0, not the real enclave base.
![1642249271(1)](https://user-images.githubusercontent.com/35480440/149621568-85c212ca-d26b-4298-9bfc-b3c95e10e72a.jpg)

While enclave base should suppose to be 0x7ffff6000000
<img width="717" alt="1642249854(1)" src="https://user-images.githubusercontent.com/35480440/149621825-5053a570-fd2a-4515-90cf-e9d2f5605aeb.png">

I also know that __ImageBase is defined in build system
![image](https://user-images.githubusercontent.com/35480440/149621582-1043d080-4d29-40b8-b069-64db7ba35642.png)

And I confirm that __ImageBase is at `0` address of `enclave.signed.so`
![image](https://user-images.githubusercontent.com/35480440/149621610-f7ee376c-f65f-48e7-bc95-4fc414e017a6.png)

So my question is why `&__ImageBase` does not point to enclave base any more, and how can I fix this

Urgently need help!!!

On the other side, when everything work correctly, link with ld, then `g_enclave_base` become `0x7ffff6000000` while `&__ImageBase` is still `0`, it's weird.
<img width="1152" alt="3980d94799be65c66f8bf70954b4264" src="https://user-images.githubusercontent.com/35480440/149622239-8acef44c-56e3-4fc1-a7f9-9c973b1bb963.png">

**Comment by LeoneChen** [comment] 2022-01-15 15:15
I find -defsym option in gnu ld is specify symbol address. (-0x30297+$rip) point to `__ImageBase` symbol, and then get address of __ImageBase
![image](https://user-images.githubusercontent.com/35480440/149626583-ff14aed9-13a3-455d-97a0-fb088551b07a.png)

while -defsym option in llvm lld, specify symbol absolute address, which will not modify when dynamic object base address changes, since lld save `__ImageBase` address at certain memory position, and directly read `__ImageBase` address from this memory position
![1642259475(1)](https://user-images.githubusercontent.com/35480440/149626752-a0484d4a-b3a9-4125-8888-78ac352e0b90.jpg)

**Comment by LeoneChen** [comment] 2022-01-16 06:52
Any idea to fix this problem is helpful! Thanks!

**Comment by lzha101** [comment] 2022-01-17 02:26
Seems you have found the root cause of this issue.  The lld you are using is not compatible with SGX implementation.
Can you try to modify the `init_enclave.cpp` to call `get_enclave_base()` instead of directly referring to the `__ImageBase`?  I have no chance to try your case.  Hope it could be helpful.

**Comment by LeoneChen** [comment] 2022-01-17 04:30
> Seems you have found the root cause of this issue. The lld you are using is not compatible with SGX implementation. Can you try to modify the `init_enclave.cpp` to call `get_enclave_base()` instead of directly referring to the `__ImageBase`? I have no chance to try your case. Hope it could be helpful.

So thanks! This works! And I found we should replace all `&__ImageBase` usage with `get_enclave_base()`. Why not the implementation of sgxsdk directly use `get_enclave_base()` instead of `&__ImageBase`? Since `get_enclave_base()` takes much more overhead (it will add extra call instruction)?

**Comment by lzha101** [comment] 2022-01-18 08:06
Cannot recall the reason now.  IMO, we can change the C code to make the code more compatible with other build toolchain.  The change will be in later release.

BTW, is this the only one issue to use LLVM to build SGX?

**Comment by LeoneChen** [comment] 2022-01-19 07:06
I can't ensure there is no other issues, but currently, everything works well on my tested SGX APP.

Thanks to your answer again!

**Closed** 2022-01-24 10:54 UTC
