### ISSUE TITLE
"Programming Reference" link in README.md needs update?

### ISSUE THREAD

**Issue by flihp** [intel/linux-sgx#322] opened 2018-09-28 19:54 UTC
I'm running through the README.md while installing the SDK. The README.md references the `Intel(R) SGX Programming Reference` in the documentation section but the linked document has a release date of 2014. That seems way to old given the latest release in the github repo is from just a few hours ago.

I tried to track down a newer version of the document and ended up here: https://software.intel.com/en-us/sgx-sdk/documentation. The URL looks right, but every link to the Linux documentation on that page results in a 404 :worried:. The Windows documentation is right where it should be though.

Any chance I can get someone to fix up the link in the README.md so that it points to the latest / correct programming reference for Linux? Fixing up those 404s on the Intel website would also help keep others from wasting time combing though the same deadends I've been running into.

Looks like the right docs are here: https://download.01.org/intel-sgx/linux-2.3.1/docs/?

**Comment by avchinch** [comment] 2018-10-01 12:12
Thanks for pointing this out, we will update the readme in github and fix the broken link on IDZ.

The specific link you're referring to is for an old document that captures SGX info from the SDM. The closest replacement would be a link to the latest SDM, Volume 3.
https://software.intel.com/en-us/articles/intel-sdm

As you suggested, this is the correct location for the Linux SGX Developer's Guide and Developer's Reference:
https://01.org/intel-software-guard-extensions/downloads

**Comment by lzha101** [comment] 2018-12-27 06:54
The issue is fixed as the link for Programming Reference is recovered.  Close this.

**Closed by lzha101** 2018-12-27 06:54 UTC
