### ISSUE TITLE
get_launch_token timeout during creation is SGX_ERROR_UNEXPECTED

### ISSUE THREAD

**Issue by deeglaze** [intel/linux-sgx#158] opened 2017-09-12 22:32 UTC
In urts/launch_checker.cpp, there is a call to ::get_launch_token, which periodically fails in our test apparatus. After a lot of instrumentation, I found that the problem comes from

oal_get_launch_token returns UAE_OAL_ERROR_UNEXPECTED because
servicesProvider->InternalInterface returns UAE_OAL_ERROR_UNEXPECTED because
mTransport->transact fails because
receiveMessage fails because
sock->readRaw(sizeof(AEMessage::size)) fails.

Note there is no timeout detected here. What should I do as a user?

**Comment by andyzyb** [comment] 2017-09-13 01:47
The launch token is retrieved from AESM service.  It looks there is some issue in communicating with AESM through socket.   May you check if AESM service is successfully running.

**Comment by deeglaze** [comment] 2017-09-13 16:40
My AESM service is running. If I run my test 100 times on the same machine, it fails roughly 3 times.

**Comment by haitaohuang** [comment] 2017-09-14 02:06
Can you  provide more details like how many concurrent clients, frequency of the requests? Does failure happen randomly or happen after some long testing session?

Do you see AESM crash when failure happens? It may be restarted automatically if crashed. You can check the syslogs to see it.

The title of this issue suggests a timeout. From what I see, the timeout is set as 10 min for DEBUG builds or 15 seconds for release build in uae_service/config.h. It should be unlikely to happen in normal conditions.
 
.

**Comment by deeglaze** [comment] 2017-09-14 15:30
Where would I find the log? Sorry for the issue title. I started the issue mid-diagnosis and forgot the update it when I found it wasn't a (detected) timeout. Failure is random. A test following this failure will often succeed.

**Comment by haitaohuang** [comment] 2017-09-14 16:41
logs are in  /var/log/syslog

**Comment by haitaohuang** [comment] 2017-09-14 16:51
Another way to check if aesm restarted is to check the running time when you check the status

"systemctl status aesmd.service" will output something like following and  running time is shown in the highlighted line.

● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   **Active: active (running) since Thu 2017-09-14 11:47:45 CDT; 1s ago**
  Process: 21205 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 21200 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 21198 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 21195 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
 Main PID: 21206 (aesm_service)
   CGroup: /system.slice/aesmd.service
           └─21206 /opt/intel/sgxpsw/aesm/aesm_service

**Comment by deeglaze** [comment] 2017-09-15 17:51
Nothing in syslog and the service has been up since I last updated it 3 days ago.

**Comment by haitaohuang** [comment] 2017-09-15 20:57
Thanks for the update. Unfortunately we still need more info to reproduce the issue.  You mentioned about 3% failure rate.  Did the failures happen in a single app that was calling get token in loop? or multiple instances of the same app?
You may also consider retrying create_enclanve or get_launch_token if the failure is recoverable and that's acceptable workaround before we can root cause.

**Comment by deeglaze** [comment] 2017-09-15 23:22
This is a single app run started and run multiple times serially. The problem with retrying with the uRTS currently is that SGX_ERROR_UNEXPECTED is a code smell that I'd need to fix first. What is a suitable error code to use in my case? I'll start with the timeout error.

**Comment by haitaohuang** [comment] 2017-09-16 16:34
The only thing suspicious based on reading the code is that signal interrupts are not checked for epoll_wait calls. Here is the patch for that: https://github.com/haitaohuang/linux-sgx/commit/d31aad821a54f2820c0cd8ccb20c501ebd6ba782

Can you also modify the sample enclave like this:https://github.com/haitaohuang/linux-sgx/commit/d7247aa7baa225219778fab7620dea88468cc466, and run the test_token script on your side?

Not sure I understand your question about the error code. The only other cases should not be SGX_ERROR_UNEXPECTED are cases of invalid inputs. Here is what I mean:https://github.com/haitaohuang/linux-sgx/commit/f02bf07d548b7ba56f709950747d522b1c8ce28c
But those cases are unlikely, and one would argue they are unexpected.

**Comment by haitaohuang** [comment] 2017-09-17 05:09
The only thing suspicious based on reading the code is that signal interrupts are not checked for epoll_wait calls. Here is the patch for that: https://github.com/haitaohuang/linux-sgx/commit/d31aad821a54f2820c0cd8ccb20c501ebd6ba782

Can you also modify the sample enclave like this:https://github.com/haitaohuang/linux-sgx/commit/d7247aa7baa225219778fab7620dea88468cc466, and run the test_token script on your side?

Not sure I understand your question about the error code. The only other cases should not be SGX_ERROR_UNEXPECTED are cases of invalid inputs. Here is what I mean:https://github.com/haitaohuang/linux-sgx/commit/f02bf07d548b7ba56f709950747d522b1c8ce28c
But those cases are unlikely, and one would argue they are unexpected.

**Comment by haitaohuang** [comment] 2017-09-17 05:24
accidentally closed...

After more careful review of the code, I think the socket related code are not handling signals at other places where read/write/epoll_wait are called.

Created a patch to fix those: https://github.com/haitaohuang/linux-sgx/commit/0075d69adde730b3cb7dd45eb8de4b7a6f7d9c99

Created test case based on SampleEnclave: https://github.com/haitaohuang/linux-sgx/commit/9d595aa59052748314162cb3498c62cd098b4f30

You may want to try those two patches to verify if signals indeed are causing the problems on your side. To test, first run the modified SampleEnclave/app, then use the kill_app.sh script to send signal to the running app. 

I reproduced/encountered unexpected error if I don't have the two driver commits made on this branch https://github.com/haitaohuang/linux-sgx-driver/commits/signal or the uae_service patch above.

After applying those patches, the test runs fine.

I also included the input error code patch (https://github.com/haitaohuang/linux-sgx/commit/383ce87b7b9714d28fc0afd93b77de7e1d0adf69), but it has no effect to the modified sample app.

**Comment by llly** [comment] 2017-09-18 08:55
@haitaohuang Thanks a lot for finding the root cause.  [haitaohuang/linux-sgx@0075d69](https://github.com/haitaohuang/linux-sgx/commit/0075d69adde730b3cb7dd45eb8de4b7a6f7d9c99) doesn't rely on [haitaohuang/linux-sgx-driver@3f01](https://github.com/haitaohuang/linux-sgx-driver/commit/3f01639a96e829e5c9a57f80c50875be5b050cb6), right? So we can update both repo in parallel.

**Comment by haitaohuang** [comment] 2017-09-18 13:39
yes, there are no build time dependencies between those two

**Comment by haitaohuang** [comment] 2017-09-22 17:08
Now the PR is merged. Please verify if this fixes the original issue. Note the driver patches mentioned in PR are still needed to eliminate other unexpected errors given by uRTS for unhandled errors (EINTR and EINVAL) from driver IOCs.

**Closed** 2018-07-31 05:58 UTC
