### ISSUE TITLE
Fail on implement unordered_map in enclave.

### ISSUE THREAD

**Issue by DanistyWuKids** [intel/linux-sgx#388] opened 2019-04-03 12:23 UTC
It starts to have errors while trying to create a new unordered map array in the enclave.
with statement:
`#include<unordered_map>`
`std::unordered_map<std::string, int>enclave map`
Output while making:
`
In file included from /opt/intel/sgxsdk/include/libcxx/unordered_map:368:0,
                 from Enclave/Enclave.cpp:5:
/opt/intel/sgxsdk/include/libcxx/type_traits: In instantiation of ‘struct std::__1::__is_constructible1_imp<false, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, const std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>&>’:
/opt/intel/sgxsdk/include/libcxx/type_traits:3111:8:   required from ‘struct std::__1::__is_constructible1_void_check<false, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, const std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>&>’
/opt/intel/sgxsdk/include/libcxx/type_traits:3161:30:   required from ‘struct std::__1::is_constructible<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, const std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>&, std::__1::__is_construct::__nat>’
/opt/intel/sgxsdk/include/libcxx/type_traits:3227:30:   required from ‘struct std::__1::is_copy_constructible<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true> >’
/opt/intel/sgxsdk/include/libcxx/__hash_table:1479:5:   required from ‘std::__1::__hash_table<_Tp, _Hash, _Equal, _Alloc>::~__hash_table() [with _Tp = std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>; _Hash = std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>; _Equal = std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>; _Alloc = std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> >]’
/opt/intel/sgxsdk/include/libcxx/unordered_map:801:9:   required from ‘std::__1::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map() [with _Key = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >; _Tp = int; _Hash = std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >; _Pred = std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >; _Alloc = std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> >]’
Enclave/Enclave.cpp:16:38:   required from here
/opt/intel/sgxsdk/include/libcxx/type_traits:3071:18: error: forming reference to reference type ‘const std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>&’
                  decltype(__is_constructible1_test(declval<_Tp&>(), declval<_A0&>()))
                  ^
/opt/intel/sgxsdk/include/libcxx/__hash_table: In instantiation of ‘std::__1::__hash_table<_Tp, _Hash, _Equal, _Alloc>::~__hash_table() [with _Tp = std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>; _Hash = std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>; _Equal = std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>; _Alloc = std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> >]’:
/opt/intel/sgxsdk/include/libcxx/unordered_map:801:9:   required from ‘std::__1::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map() [with _Key = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >; _Tp = int; _Hash = std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >; _Pred = std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >; _Alloc = std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> >]’
Enclave/Enclave.cpp:16:38:   required from here
/opt/intel/sgxsdk/include/libcxx/__hash_table:1479:5: error: ‘value’ is not a member of ‘std::__1::is_copy_constructible<std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true> >’
     static_assert((is_copy_constructible<key_equal>::value),
     ^
/opt/intel/sgxsdk/include/libcxx/__hash_table:1481:5: error: ‘value’ is not a member of ‘std::__1::is_copy_constructible<std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true> >’
     static_assert((is_copy_constructible<hasher>::value),
     ^
Makefile:210: recipe for target 'Enclave/Enclave.o' failed
`

**Comment by xxu36** [comment] 2019-04-08 03:09
Do you have access to Cxx11SGXDemo project under SampleCode folder? There is an unordered_map case at about line 600. Can you pass that test case?

**Comment by ZongminGu** [comment] 2019-04-08 03:15
You need to #include <string> since you are using std::string as the template. It is not the SGX SDK bug.

**Comment by DanistyWuKids** [comment] 2019-04-08 03:32
> You need to #include <string> since you are using std::string as the template. It is not the SGX SDK bug.

I did include with <String> in the enclave.cpp.

Here are all the head files that I included:
`#include<stdio.h>`
`#include<stdlib.h>`
`// #include<memory>`
`// #include<map>`
`#include <unordered_map>`
`#include <stdarg.h>`
`#include <string.h>`
`#include <string>`

`#include "sgx_trts.h"`
`#include "sgx_tcrypto.h"`

`#include "Enclave_t.h"`

I am wondering if there has conflict happens within those head files?

**Comment by DanistyWuKids** [comment] 2019-04-08 03:36
> Do you have access to Cxx11SGXDemo project under SampleCode folder? There is an unordered_map case at about line 600. Can you pass that test case?

Yes, I did, I had tested in both SIM and HW mode, that code runs fine,  I did see that have some simple activity do with the unordered_map in the code. But I am wishing to transfer the whole unordered_map via OCALL or ECALL, is that possible? Or I have to do that in alternative ways? (So far I am transferring the elements one by one rather than the whole map).

**Comment by andyzyb** [comment] 2019-04-08 03:38
I think the recommendation is to use a consistent style to include header files, looks you are using both C header files and C++ header file together.  Would you please try to use C++ header files only?  For example, stdio.h -> cstdio,  stdlib.h -> cstdlib,  string.h -> cstring, etc.

**Comment by andyzyb** [comment] 2019-04-08 03:42
Transferring a whole map would be a problem because you have to handle all the object initialization, while ECALL and OCALL just do the data copy and won't call any constructors, and it won't parse any internal data structure of map, so likely some internal state/data won't be copied either.

**Comment by ZongminGu** [comment] 2019-04-08 04:03
If I include all the header files as you listed, I am not able to reproduce the issue.

**Comment by DanistyWuKids** [comment] 2019-04-10 13:13
> I think the recommendation is to use a consistent style to include header files, looks you are using both C header files and C++ header file together. Would you please try to use C++ header files only? For example, stdio.h -> cstdio, stdlib.h -> cstdlib, string.h -> cstring, etc.

Thanks for your advice, I have follwed the style that in Cxx11SGXDemo, which by putting unordered map to a separate file under a folder in Enclave, then it seems work, so I guess you are right, there might have some conflict on those headers.

**Closed** 2019-04-10 13:13 UTC
