### ISSUE TITLE
Documentation update for JHI build and install

### ISSUE THREAD

**Issue by richardatlateralblast** [intel/linux-sgx#336] opened 2018-10-31 21:27 UTC
Just a note to say documentation for JHI build and install on Ubuntu should include libsystemd-dev as part of the package install, i.e.

$ sudo apt-get install uuid-dev libxml2-dev cmake pkg-config

should be:

$ sudo apt-get install uuid-dev libxml2-dev cmake pkg-config libsystemd-dev

Otherwise compile will fail and complain about systemd/sd-daemon.h being missing

**Comment by lzha101** [comment] 2018-11-01 07:00
Thanks for reporting this. It will be fixed in next release.

**Comment by lzha101** [comment] 2018-12-27 06:41
The issue is fixed by updating the [README.md](https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites-2). So close this issue.

**Closed by lzha101** 2018-12-27 06:41 UTC
