### ISSUE TITLE
std::shared_ptr is not thread safe

### ISSUE THREAD

**Issue by cblokh** [intel/linux-sgx#932] opened 2023-01-19 14:44 UTC
In sgx_2.18 libsgx_tcxx is compiled with `#define _LIBCPP_HAS_NO_THREADS` which causes `__libcpp_atomic_refcount_increment` and `__libcpp_atomic_refcount_decrement` to be implemented as non atomic operation

**Comment by cblokh** [comment] 2023-01-19 16:38
the code of `__shared_count::__add_shared` was changed to call  `__libcpp_atomic_refcount_increment` that checks this define

**Comment by henrywang8atfbdotcom** [comment] 2023-01-19 22:42
Just curious, what kind of manifestations you see, random segfaults with shared_ptrs inside Enclave?

**Comment by cblokh** [comment] 2023-01-20 15:02
yes

**Comment by cblokh** [comment] 2023-01-20 15:10
I created this [pull request](https://github.com/intel/linux-sgx/pull/933), it solves my issue but there can be other places that still doesn't perform atomic operations

**Comment by henrywang8atfbdotcom** [comment] 2023-01-22 14:33
Do you have a minimal reproducible example that demonstrates non-atomic shared_ptr causing segfaults. We have some usages of shared_ptrs in our Enclave code, but I haven't seen this happen yet.

**Comment by cblokh** [comment] 2023-01-22 15:30
This should reproduce it
[shared_ptr_demo.zip](https://github.com/intel/linux-sgx/files/10474742/shared_ptr_demo.zip)

**Comment by henrywang8atfbdotcom** [comment] 2023-01-23 04:13
Wow thanks a lot, I see the segmentation fault too.

**Comment by henrywang8atfbdotcom** [comment] 2023-01-24 03:45
Ok turns out I got the repro wrong  - I had a bug. But it turns out we don't use tlibcxx anyways, so I'm actually not able to reprod/test this.

**Comment by cblokh** [comment] 2023-01-24 09:31
it does use it, you can see the problem by doing `objdump -d -M intel enclave.so | c++filt | grep -A3 "__add_shared()>:"`
with the original libsgx_tcxx you will see:
`add    QWORD PTR [rdi+0x8],0x1`
and with the patched version
`lock add QWORD PTR [rdi+0x8],0x1`

**Comment by henrywang8atfbdotcom** [comment] 2023-01-24 17:48
What I meant is that we have significant modifications to the SDK that we maintain as well as the customizations to the toolchain. So right now, our build system does not use tlibcxx which is why I was not able to reproduce this issue. Instead, we use other libs to provide stdc++ header/symbols. Don't ask me why it's like this, I only inherited it.

But thanks a lot for helping!

**Comment by lzha101** [comment] 2023-03-30 03:09
The PR https://github.com/intel/linux-sgx/pull/933 is merged. Looks we can close this issue.

**Closed by lzha101** 2023-03-30 03:09 UTC

**Comment by cblokh** [comment] 2023-04-04 15:11
Thanks
