### ISSUE TITLE
DEBUG=1 make sdk fails with GCC8

### ISSUE THREAD

**Issue by mythi** [intel/linux-sgx#325] opened 2018-10-03 12:06 UTC
```
...
make -C ukey_exchange
make[3]: Entering directory '/home/clr/sgx/fedora27-server/linux-sgx-sgx_2.3.1/sdk/ukey_exchange'
g++ -g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,--copy-dt-needed-entries -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-signed-zeros -fno-trapping-math  -fassociative-math -Wl,-sort-common -Wl,--enable-new-dtags -fvisibility-inlines-hidden -Wl,--enable-new-dtags  -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O0 -ggdb -DDEBUG -UNDEBUG -DSE_DEBUG_LEVEL=SE_TRACE_DEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O0 -ggdb -DDEBUG -UNDEBUG -DSE_DEBUG_LEVEL=SE_TRACE_DEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O0 -ggdb -DDEBUG -UNDEBUG -DSE_DEBUG_LEVEL=SE_TRACE_DEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O0 -ggdb -DDEBUG -UNDEBUG -DSE_DEBUG_LEVEL=SE_TRACE_DEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -Werror -fPIC -fno-exceptions -fno-rtti  -I/home/clr/sgx/fedora27-server/linux-sgx-sgx_2.3.1/common/inc/internal -I/home/clr/sgx/fedora27-server/linux-sgx-sgx_2.3.1/common/inc -I/home/clr/sgx/fedora27-server/linux-sgx-sgx_2.3.1/external/ippcp_internal/inc    -c -o ukey_exchange.o ukey_exchange.cpp
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib64/gcc/x86_64-generic-linux/8.2.1/include/stdint.h:9,
                 from ukey_exchange.cpp:40:
/usr/include/features.h:381:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
cc1plus: all warnings being treated as errors
```

It builds OK witthout ```DEBUG=1```, i.e., ```make clean && make sdk``` succeeds.

```
$ g++ --version
g++ (Clear Linux OS for Intel Architecture) 8.2.1 20180502
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mythi** [comment] 2018-10-09 10:48
The problem is that unwanted (i.e., EPID SDK's) ```CXXFLAGS``` leak to builds after epid-sdk is built. One option could be to make ```buildenv.mk``` self-contained:

```
diff --git a/buildenv.mk b/buildenv.mk
index 1d32d277..b22a2eee 100644
--- a/buildenv.mk
+++ b/buildenv.mk
@@ -105,10 +105,10 @@ COMMON_FLAGS += -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type \
                -Wcast-align -Wconversion -Wredundant-decls
 
 # additional warnings flags for C
-CFLAGS += -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants
+CFLAGS = -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants
 
 # additional warnings flags for C++
-CXXFLAGS += -Wnon-virtual-dtor
+CXXFLAGS = -Wnon-virtual-dtor
 
 CXXFLAGS += -std=c++11
```

with this change, you can also add ```-Werror``` back

```
 diff --git a/psw/ae/pse/pse_pr/Makefile b/psw/ae/pse/pse_pr/Makefile
index 35bb99d8..c93c0849 100644
--- a/psw/ae/pse/pse_pr/Makefile
+++ b/psw/ae/pse/pse_pr/Makefile
@@ -33,7 +33,7 @@ TOP_DIR := ../../../..
 include ../../buildenv.mk
 
 CFLAGS   += -Werror
-#CXXFLAGS += -Werror
+CXXFLAGS += -Werror
 
 EPID_SDK_DIR := $(TOP_DIR)/external/epid-sdk/
```

**Comment by lzha101** [comment] 2018-10-11 08:44
Thanks for reporting this and root causing the problem.  We will consider to fix this later.

From the command line you posted here, some of the options are not from SGX Makefiles, such as `--param=ssp-buffer-size=32`.  I don't know why these options are added if you build SGX directly with command `make DEBUG=1`.  Are you building some other projects in the same process of building SGX?

**Comment by mythi** [comment] 2018-10-11 09:38
@lzha101 Nice catch. that helped me to realize what's going on. my ```CFLAGS``` on Clear Linux are set by a global user environment setting and they are in conflict with ```DEBUG=1``` and enclaves overall.

> We will consider to fix this later.

I think this issue can be closed.

**Comment by lzha101** [comment] 2018-10-12 00:47
Good to know that the failure is not caused by SGX build scripts.  Close this issue.  
BTW,  as to your recommendation of enabling `-werror` for PSE_PR, perhaps we can consider to enhance the EPID-SDK Makefile.

**Closed by lzha101** 2018-10-12 00:47 UTC
